version: '3.3'

services:
  db:
    image: postgres:10.3
    restart: always
    environment:
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
      POSTGRES_USER: sonar
    volumes:
      - ./database:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  sonarqube:
    image: sonarqube:7.0
    restart: always
    links:
      - db
    environment:
      SONARQUBE_JDBC_USERNAME: sonar
      SONARQUBE_JDBC_PASSWORD: sonar
      SONARQUBE_JDBC_URL: "jdbc:postgresql://db/sonar"
    ports:
      - "9000:9000"
      - "443"
